[package]
name = "joryu"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.2", features = ["rt-multi-thread"] }
rand = "0.9.1"
regex = "1.11.1"
anyhow = "1.0.98"

[patch."https://github.com/gentoo-based/serenity-android"]

[patch."https://github.com/gentoo-based/poise"]